### ISSUE TITLE
Update to Node 8

### ISSUE THREAD

**Issue by odzb** [MatthewHartstonge/node-docker#21]

**Comment by matthewhartstonge** [comment]
Hi @odzb,

I'll get to this when I have a spare moment. For now - Each node/docker version is split out into a separate branch. Please feel free to add Pull Requests to add the different versions you use as a token of thanks and also to give back to the community.

**Comment by matthewhartstonge** [comment]
@npeterkamps fyi, had a bit of issue with Dockerhub + automated builds since lowercasing my Github username..

I managed to automate the generation of Dockerfile's and commiting to git, but now Docker Cloud is a little overloaded with the 133 new branches/builds 😬 lol

I'll keep an eye on it, and re-push the versions that need to be built. I'll prioritize getting Node 8 out after the first batch of 30 has completed. 👌
